# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Xilinx/SoC/RISCV_Tutorial/RISCV_Tutorial.srcs/sources_1/ip/ram_2port_2048x32/ram_2port_2048x32.xci
# IP: The module: 'ram_2port_2048x32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/SoC/RISCV_Tutorial/RISCV_Tutorial.srcs/sources_1/ip/ram_2port_2048x32/ram_2port_2048x32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_2port_2048x32'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Xilinx/SoC/RISCV_Tutorial/RISCV_Tutorial.srcs/sources_1/ip/ram_2port_2048x32/ram_2port_2048x32.xci
# IP: The module: 'ram_2port_2048x32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/SoC/RISCV_Tutorial/RISCV_Tutorial.srcs/sources_1/ip/ram_2port_2048x32/ram_2port_2048x32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_2port_2048x32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
