# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Xilinx/SoC/RISCV_homework/RISCV_homework.srcs/sources_1/new/RV32I_SoC.xdc

# IP: ip/ram_2port_2048x32/ram_2port_2048x32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ram_2port_2048x32 || ORIG_REF_NAME==ram_2port_2048x32} -quiet] -quiet
