// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern void AESL_WRAP_matrixmul (
unsigned int lm,
unsigned int ln,
unsigned int lp,
unsigned char A[32][32],
unsigned char B[32][32],
unsigned int AB[32][32]);
