webtalk_init -webtalk_dir C:/Xilinx/SoC/Lab12-RV32-Start/Lab12-RV32-Start2.sim/sim_1/behav/xsim/xsim.dir/tb_RV32I_SoC_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Jun  2 21:58:41 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d0ca6082a93056f5a4260a1ece8594c3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "38f2470b31654bb7bfc52a17470327a6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "41" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2496 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "238047 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "2.12_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "9936_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4242432278 -regid "" -xml C:/Xilinx/SoC/Lab12-RV32-Start/Lab12-RV32-Start2.sim/sim_1/behav/xsim/xsim.dir/tb_RV32I_SoC_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Xilinx/SoC/Lab12-RV32-Start/Lab12-RV32-Start2.sim/sim_1/behav/xsim/xsim.dir/tb_RV32I_SoC_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Xilinx/SoC/Lab12-RV32-Start/Lab12-RV32-Start2.sim/sim_1/behav/xsim/xsim.dir/tb_RV32I_SoC_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
