// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

`timescale 1ns/1ps
module fir_AXILiteS_s_axi
#(parameter
    C_S_AXI_ADDR_WIDTH = 8,
    C_S_AXI_DATA_WIDTH = 32
)(
    // axi4 lite slave signals
    input  wire                          ACLK,
    input  wire                          ARESET,
    input  wire                          ACLK_EN,
    input  wire [C_S_AXI_ADDR_WIDTH-1:0] AWADDR,
    input  wire                          AWVALID,
    output wire                          AWREADY,
    input  wire [C_S_AXI_DATA_WIDTH-1:0] WDATA,
    input  wire [C_S_AXI_DATA_WIDTH/8-1:0] WSTRB,
    input  wire                          WVALID,
    output wire                          WREADY,
    output wire [1:0]                    BRESP,
    output wire                          BVALID,
    input  wire                          BREADY,
    input  wire [C_S_AXI_ADDR_WIDTH-1:0] ARADDR,
    input  wire                          ARVALID,
    output wire                          ARREADY,
    output wire [C_S_AXI_DATA_WIDTH-1:0] RDATA,
    output wire [1:0]                    RRESP,
    output wire                          RVALID,
    input  wire                          RREADY,
    // user signals
    input  wire [31:0]                   y,
    input  wire                          y_ap_vld,
    input  wire [3:0]                    c_address0,
    input  wire                          c_ce0,
    output wire [31:0]                   c_q0,
    output wire [31:0]                   x
);
//------------------------Address Info-------------------
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : Data signal of y
//        bit 31~0 - y[31:0] (Read)
// 0x14 : Control signal of y
//        bit 0  - y_ap_vld (Read/COR)
//        others - reserved
// 0x80 : Data signal of x
//        bit 31~0 - x[31:0] (Read/Write)
// 0x84 : reserved
// 0x40 ~
// 0x7f : Memory 'c' (11 * 32b)
//        Word n : bit [31:0] - c[n]
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

//------------------------Parameter----------------------
localparam
    ADDR_Y_DATA_0 = 8'h10,
    ADDR_Y_CTRL   = 8'h14,
    ADDR_X_DATA_0 = 8'h80,
    ADDR_X_CTRL   = 8'h84,
    ADDR_C_BASE   = 8'h40,
    ADDR_C_HIGH   = 8'h7f,
    WRIDLE        = 2'd0,
    WRDATA        = 2'd1,
    WRRESP        = 2'd2,
    WRRESET       = 2'd3,
    RDIDLE        = 2'd0,
    RDDATA        = 2'd1,
    RDRESET       = 2'd2,
    ADDR_BITS         = 8;

//------------------------Local signal-------------------
    reg  [1:0]                    wstate = WRRESET;
    reg  [1:0]                    wnext;
    reg  [ADDR_BITS-1:0]          waddr;
    wire [31:0]                   wmask;
    wire                          aw_hs;
    wire                          w_hs;
    reg  [1:0]                    rstate = RDRESET;
    reg  [1:0]                    rnext;
    reg  [31:0]                   rdata;
    wire                          ar_hs;
    wire [ADDR_BITS-1:0]          raddr;
    // internal registers
    reg  [31:0]                   int_y = 'b0;
    reg                           int_y_ap_vld;
    reg  [31:0]                   int_x = 'b0;
    // memory signals
    wire [3:0]                    int_c_address0;
    wire                          int_c_ce0;
    wire                          int_c_we0;
    wire [3:0]                    int_c_be0;
    wire [31:0]                   int_c_d0;
    wire [31:0]                   int_c_q0;
    wire [3:0]                    int_c_address1;
    wire                          int_c_ce1;
    wire                          int_c_we1;
    wire [3:0]                    int_c_be1;
    wire [31:0]                   int_c_d1;
    wire [31:0]                   int_c_q1;
    reg                           int_c_read;
    reg                           int_c_write;

//------------------------Instantiation------------------
// int_c
fir_AXILiteS_s_axi_ram #(
    .BYTES    ( 4 ),
    .DEPTH    ( 11 )
) int_c (
    .clk0     ( ACLK ),
    .address0 ( int_c_address0 ),
    .ce0      ( int_c_ce0 ),
    .we0      ( int_c_we0 ),
    .be0      ( int_c_be0 ),
    .d0       ( int_c_d0 ),
    .q0       ( int_c_q0 ),
    .clk1     ( ACLK ),
    .address1 ( int_c_address1 ),
    .ce1      ( int_c_ce1 ),
    .we1      ( int_c_we1 ),
    .be1      ( int_c_be1 ),
    .d1       ( int_c_d1 ),
    .q1       ( int_c_q1 )
);

//------------------------AXI write fsm------------------
assign AWREADY = (wstate == WRIDLE);
assign WREADY  = (wstate == WRDATA);
assign BRESP   = 2'b00;  // OKAY
assign BVALID  = (wstate == WRRESP);
assign wmask   = { {8{WSTRB[3]}}, {8{WSTRB[2]}}, {8{WSTRB[1]}}, {8{WSTRB[0]}} };
assign aw_hs   = AWVALID & AWREADY;
assign w_hs    = WVALID & WREADY;

// wstate
always @(posedge ACLK) begin
    if (ARESET)
        wstate <= WRRESET;
    else if (ACLK_EN)
        wstate <= wnext;
end

// wnext
always @(*) begin
    case (wstate)
        WRIDLE:
            if (AWVALID)
                wnext = WRDATA;
            else
                wnext = WRIDLE;
        WRDATA:
            if (WVALID)
                wnext = WRRESP;
            else
                wnext = WRDATA;
        WRRESP:
            if (BREADY)
                wnext = WRIDLE;
            else
                wnext = WRRESP;
        default:
            wnext = WRIDLE;
    endcase
end

// waddr
always @(posedge ACLK) begin
    if (ACLK_EN) begin
        if (aw_hs)
            waddr <= AWADDR[ADDR_BITS-1:0];
    end
end

//------------------------AXI read fsm-------------------
assign ARREADY = (rstate == RDIDLE);
assign RDATA   = rdata;
assign RRESP   = 2'b00;  // OKAY
assign RVALID  = (rstate == RDDATA) & !int_c_read;
assign ar_hs   = ARVALID & ARREADY;
assign raddr   = ARADDR[ADDR_BITS-1:0];

// rstate
always @(posedge ACLK) begin
    if (ARESET)
        rstate <= RDRESET;
    else if (ACLK_EN)
        rstate <= rnext;
end

// rnext
always @(*) begin
    case (rstate)
        RDIDLE:
            if (ARVALID)
                rnext = RDDATA;
            else
                rnext = RDIDLE;
        RDDATA:
            if (RREADY & RVALID)
                rnext = RDIDLE;
            else
                rnext = RDDATA;
        default:
            rnext = RDIDLE;
    endcase
end

// rdata
always @(posedge ACLK) begin
    if (ACLK_EN) begin
        if (ar_hs) begin
            rdata <= 1'b0;
            case (raddr)
                ADDR_Y_DATA_0: begin
                    rdata <= int_y[31:0];
                end
                ADDR_Y_CTRL: begin
                    rdata[0] <= int_y_ap_vld;
                end
                ADDR_X_DATA_0: begin
                    rdata <= int_x[31:0];
                end
            endcase
        end
        else if (int_c_read) begin
            rdata <= int_c_q1;
        end
    end
end


//------------------------Register logic-----------------
assign x = int_x;
// int_y
always @(posedge ACLK) begin
    if (ARESET)
        int_y <= 0;
    else if (ACLK_EN) begin
        if (y_ap_vld)
            int_y <= y;
    end
end

// int_y_ap_vld
always @(posedge ACLK) begin
    if (ARESET)
        int_y_ap_vld <= 1'b0;
    else if (ACLK_EN) begin
        if (y_ap_vld)
            int_y_ap_vld <= 1'b1;
        else if (ar_hs && raddr == ADDR_Y_CTRL)
            int_y_ap_vld <= 1'b0; // clear on read
    end
end

// int_x[31:0]
always @(posedge ACLK) begin
    if (ARESET)
        int_x[31:0] <= 0;
    else if (ACLK_EN) begin
        if (w_hs && waddr == ADDR_X_DATA_0)
            int_x[31:0] <= (WDATA[31:0] & wmask) | (int_x[31:0] & ~wmask);
    end
end


//------------------------Memory logic-------------------
// c
assign int_c_address0 = c_address0;
assign int_c_ce0      = c_ce0;
assign int_c_we0      = 1'b0;
assign int_c_be0      = 1'b0;
assign int_c_d0       = 1'b0;
assign c_q0           = int_c_q0;
assign int_c_address1 = ar_hs? raddr[5:2] : waddr[5:2];
assign int_c_ce1      = ar_hs | (int_c_write & WVALID);
assign int_c_we1      = int_c_write & WVALID;
assign int_c_be1      = WSTRB;
assign int_c_d1       = WDATA;
// int_c_read
always @(posedge ACLK) begin
    if (ARESET)
        int_c_read <= 1'b0;
    else if (ACLK_EN) begin
        if (ar_hs && raddr >= ADDR_C_BASE && raddr <= ADDR_C_HIGH)
            int_c_read <= 1'b1;
        else
            int_c_read <= 1'b0;
    end
end

// int_c_write
always @(posedge ACLK) begin
    if (ARESET)
        int_c_write <= 1'b0;
    else if (ACLK_EN) begin
        if (aw_hs && AWADDR[ADDR_BITS-1:0] >= ADDR_C_BASE && AWADDR[ADDR_BITS-1:0] <= ADDR_C_HIGH)
            int_c_write <= 1'b1;
        else if (WVALID)
            int_c_write <= 1'b0;
    end
end


endmodule


`timescale 1ns/1ps

module fir_AXILiteS_s_axi_ram
#(parameter
    BYTES  = 4,
    DEPTH  = 256,
    AWIDTH = log2(DEPTH)
) (
    input  wire               clk0,
    input  wire [AWIDTH-1:0]  address0,
    input  wire               ce0,
    input  wire               we0,
    input  wire [BYTES-1:0]   be0,
    input  wire [BYTES*8-1:0] d0,
    output reg  [BYTES*8-1:0] q0,
    input  wire               clk1,
    input  wire [AWIDTH-1:0]  address1,
    input  wire               ce1,
    input  wire               we1,
    input  wire [BYTES-1:0]   be1,
    input  wire [BYTES*8-1:0] d1,
    output reg  [BYTES*8-1:0] q1
);
//------------------------Local signal-------------------
reg  [BYTES*8-1:0] mem[0:DEPTH-1];
//------------------------Task and function--------------
function integer log2;
    input integer x;
    integer n, m;
begin
    n = 1;
    m = 2;
    while (m < x) begin
        n = n + 1;
        m = m * 2;
    end
    log2 = n;
end
endfunction
//------------------------Body---------------------------
// read port 0
always @(posedge clk0) begin
    if (ce0) q0 <= mem[address0];
end

// read port 1
always @(posedge clk1) begin
    if (ce1) q1 <= mem[address1];
end

genvar i;
generate
    for (i = 0; i < BYTES; i = i + 1) begin : gen_write
        // write port 0
        always @(posedge clk0) begin
            if (ce0 & we0 & be0[i]) begin
                mem[address0][8*i+7:8*i] <= d0[8*i+7:8*i];
            end
        end
        // write port 1
        always @(posedge clk1) begin
            if (ce1 & we1 & be1[i]) begin
                mem[address1][8*i+7:8*i] <= d1[8*i+7:8*i];
            end
        end
    end
endgenerate

endmodule

